ref(breakdowns): Rename all fields in span operation breakdown config to camel case take 2
getsentry/relay pull request #1020
Opened 2021-06-14 20:14 UTC by dashed

Replacement for https://github.com/getsentry/relay/pull/993 with some safeguards.

I've added the serde attribute to catch for all unknown enum variants for `enum BreakdownConfig`.

2021-06-14 20:17 UTC, dashed commented on relay-general/src/store/normalize/breakdowns.rs
>  pub enum BreakdownConfig {
@untitaker I couldn't really use `enum ErrorBoundary<T>` in the project config (https://github.com/getsentry/relay/blob/a231a2b17a71304a19710cf9a49b21fa06e25f71/relay-general/src/store/mod.rs#L55) as it's in a different crate (https://github.com/getsentry/relay/blob/a231a2b17a71304a19710cf9a49b21fa06e25f71/relay-server/src/utils/error_boundary.rs).

I'm assuming this is what you had in mind. 

If so, we might need to consolidate `enum ErrorBoundary<T>` somewhere, and implement `Default` for `enum ErrorBoundary<T>`.

2021-06-14 21:45 UTC, untitaker approved these changes

2021-06-14 21:45 UTC, untitaker commented on relay-general/src/store/normalize/breakdowns.rs
> +            _ => None,
```suggestion
            BreakdownConfig::Unsupported => None,
```

If new breakdown variant is added, one should not forget to implement it..

2021-06-16 07:04 UTC, jan-auer requested changes
Looks good. The "V2" looks a bit strange at first, but is a good and explicit solution.

One change requested below, since this PR touches more places than required.

Note that once you merge and deploy this, Relay will no longer compute breakdowns until the corresponding Sentry PR is merged.

2021-06-16 07:04 UTC, jan-auer commented on relay-general/benches/benchmarks.rs
> +        breakdowns_v2: None,
The store config does not have to be renamed, since this is just an internal type.

2021-06-16 07:21 UTC, dashed commented
>  @jan-auer  Note that once you merge and deploy this, Relay will no longer compute breakdowns until the corresponding Sentry PR is merged.

Yep, I'm aware. That should be fine as the computed breakdown are not critical to the product.

2021-06-16 07:22 UTC, dashed commented on relay-general/benches/benchmarks.rs
> +        breakdowns_v2: None,
You're right. I've renamed this back to `breakdowns`.

2021-06-16 07:29 UTC, jan-auer approved these changes
Thanks!

@untitaker can you please also confirm that you're +1 on keeping StoreConfig as-is?

2021-06-16 13:28 UTC, untitaker approved these changes

2021-06-16 13:29 UTC, untitaker commented
I presume the places where we still have this as public API don't get breakdowns anyway

2021-06-16 16:25 UTC, merged