chore(replays): Disable PII scrubbing for recording events
getsentry/relay pull request #1813
Opened 2023-02-02 23:08 UTC by cmanallen

Replays are currently broken right now so we want to disable the scrubber until we figure out how to fix it.

2023-02-02 23:39 UTC, bruno-garcia approved these changes
Rather we remove this than have 50% of replays broken

2023-02-03 02:31 UTC, JoshFerge approved these changes

2023-02-03 08:51 UTC, jan-auer requested changes
Please do not comment out code to control features. Instead, introduce a flag on the project config and set it from Sentry (e.g. via flagr or some other means).

2023-02-03 09:41 UTC, jan-auer commented
Given the urgency, I took the liberty to create #1814. Thank you still for creating this PR.

2023-02-03 09:41 UTC, closed without merging

2023-02-03 14:11 UTC, cmanallen commented
@jan-auer Ah sorry I'm still learning.  My bad....  Thank you!!  You're the MVP :D