feat(replays): lower max replay recording segment size to 10 MiB
getsentry/relay pull request #2031
Opened 2023-04-13 18:07 UTC by JoshFerge

- [x] Update the config to include two separate values for maximum replay size: one for compressed size (called `max_replay_compressed`) and one for uncompressed size `max_replay_uncompressed_size`. The original value now represents the uncompressed size (`100 MiB`), which is utilized during processing. The new value, `max_replay_compressed`, is applied during the ingest stage.
- [x] Replays formerly relied on the maximum attachment limit of 100 MiB. Now, they use the new max_replay_compressed_size (`10 MiB`) setting for check_envelope_size_limits.

We are making this change as we have done analysis around our payload sizes, and if replays are above this size there is usually something off with them (mass mutation bugs, accidental inclusion of files, old SDK versions, etc.)

2023-04-13 18:54 UTC, bruno-garcia approved these changes
RSLGTM!

2023-04-14 09:32 UTC, olksdr requested changes
I left few questions, before approving this. 

Also you like to get @jjbayer opinion on the naming here.

2023-04-14 09:32 UTC, olksdr commented on CHANGELOG.md
> +
It doesn't seem like a breaking change to me.

You just changing the defaults and the configuration itself will be done somewhere else, which can still contain the old numbers.  And also can be rolled out completely unrelated to this PR.  From the Relay POV nothing breaking is happening.

2023-04-14 09:32 UTC, olksdr commented on relay-config/src/config.rs
> -    max_replay_size: ByteSize,
Can we keep old config  and use `max_replay_size` as incoming check, the one is currently called `max_replay_compressed_size`, which clearly signals what the check is for, and if this is really necessary also use `serde` alias to rename it to the new name?

What do you think?

2023-04-14 09:32 UTC, olksdr commented on relay-config/src/config.rs
> +    /// Returns the maximum payload size for an compressed replay.
```suggestion
    /// Returns the maximum payload size for a compressed replay.
```

2023-04-17 11:56 UTC, jjbayer commented on relay-config/src/config.rs
> -    max_replay_size: ByteSize,
The new naming looks OK to me, but I would add the old name as an `alias` as @olksdr suggests, such that this is not a breaking change.

2023-04-17 11:56 UTC, jjbayer commented on CHANGELOG.md
> +
+1 on moving this line to `** Internal **`.

2023-04-17 11:56 UTC, jjbayer commented on CHANGELOG.md
> +- Lower max compressed replay recording segment size to 10 MiB. ([#2031](https://github.com/getsentry/relay/pull/2031))
```suggestion
- Lower default max compressed replay recording segment size to 10 MiB. ([#2031](https://github.com/getsentry/relay/pull/2031))
```

2023-04-18 05:20 UTC, olksdr reviewed
Once the changelog updated , this should be good to go.

2023-04-18 05:20 UTC, olksdr commented on CHANGELOG.md
> +- Lower default max compressed replay recording segment size to 10 MiB. ([#2031](https://github.com/getsentry/relay/pull/2031))
Please, merge master in and move this record to `Unreleased` section.

2023-04-18 07:00 UTC, jjbayer approved these changes
See @olksdr 's changelog comments, otherwise LGTM!

2023-04-18 17:59 UTC, JoshFerge commented
@bmckerry has increased the max message size of our kafka topic, this and https://github.com/getsentry/relay/pull/2032 should be good to go! can merge once approved. can deploy this one first, then 2032 subsequently.

2023-04-19 05:07 UTC, olksdr approved these changes

2023-04-19 17:11 UTC, merged