feat(profiling): Extract app identifier from app context
getsentry/relay pull request #2172
Opened 2023-06-01 21:01 UTC by Zylphrex

To improve the in app detection on profiles, we need the app identifier from the app context. Going forwards, when the app identifier exists on android profiles, only modules that start with the app identifier will be classified as in app.

2023-06-02 09:51 UTC, iker-barriocanal requested changes
The PR looks good to me! Could we add some tests to ensure this works as intended?

2023-06-02 17:21 UTC, phacops approved these changes

2023-06-02 17:21 UTC, phacops commented on relay-profiling/src/extract_from_transaction.rs
> -    if let Some(dist) = event.dist.value() {
I feel like I wanted to extract something else but never renamed it and I forgot what it was.

2023-06-05 07:27 UTC, iker-barriocanal approved these changes

2023-06-05 07:27 UTC, iker-barriocanal commented on relay-profiling/src/extract_from_transaction.rs
> +            BTreeMap::from([
nit: if you want to check the whole object and not just a couple of keys, consider using a snapshot instead. See [`insta::assert_debug_snapshot!`](https://github.com/getsentry/relay/blob/ed39746ec4b6cee3066f19d0cae54198bbe32971/relay-filter/src/config.rs#L236) if you prefer an in-line snapshot or [`insta::assert_annotated_snapshot!`](https://github.com/getsentry/relay/blob/ed39746ec4b6cee3066f19d0cae54198bbe32971/relay-general/src/pii/convert.rs#L450) if you prefer to have it in another file. Another benefit of using insta snapshots is that you can run `cargo insta review` and update them automatically, more convenient than modifying keys manually.

2023-06-06 14:33 UTC, merged