fix(crons): Limit environment names on check-ins to 64 chars
getsentry/relay pull request #2309
Opened 2023-07-13 17:50 UTC by rjo100

Restricts max_chars on environment names.

Helps close SENTRY-1351

#skip-changelog

2023-07-14 14:05 UTC, jjbayer requested changes
The `metastructure` attribute only works in combination with `Annotated`. I think we need to do some manual work here, similar to `trim_slug`.

2023-07-14 17:04 UTC, rjo100 commented
is there any way to directly import this value instead? can add in the copycat `trim_slug` after
https://github.com/getsentry/relay/blob/3ec78a1fb4b687dbf5c7c77149126bb1b4e69ebc/relay-general/src/processor/attrs.rs#L134

2023-07-17 11:45 UTC, jjbayer commented
> is there any way to directly import this value instead? can add in the copycat `trim_slug` after
> 
> https://github.com/getsentry/relay/blob/3ec78a1fb4b687dbf5c7c77149126bb1b4e69ebc/relay-general/src/processor/attrs.rs#L134

You can either add `relay-general` to this crate's Cargo.toml and then use `MaxChars::Environment.limit()`, or (to avoid an additional dependency), define a new constant in `relay-common` and import it from both here and  `MaxChars::limit()`.

2023-07-18 07:51 UTC, jjbayer requested changes
Almost there, see two remaining comments.

2023-07-18 07:51 UTC, jjbayer commented on relay-monitors/src/lib.rs
> +    if check_in.environment.len() > ENVIRONMENT_LENGTH {
Here I think you want the number of chars, not the number of bytes. Rust is nasty.

```suggestion
    if check_in.environment.chars().count() > ENVIRONMENT_LENGTH {
```

2023-07-18 07:51 UTC, jjbayer commented on relay-crash/sentry-native
Could you check why this submodule was updated?

2023-07-18 16:48 UTC, rjo100 commented on relay-crash/sentry-native
Oh hm didn't mean to do that

2023-07-19 06:24 UTC, olksdr reviewed
Left few suggestions. 

I'm not sure we want to rely on `relay-general` crate though, it's quite big with a lot of deps as well, and it would be better to keep the `relay-monitors` somewhere with smaller footprint.

2023-07-19 06:24 UTC, olksdr commented on CHANGELOG.md
> +- Limit environment names on check-ins to 64 chars. ([#2309](https://github.com/getsentry/relay/pull/2309))
Could you, please, move this to `Unreleased` section of the changelog

2023-07-19 06:24 UTC, olksdr commented on relay-monitors/src/lib.rs
> +    /// Environment name was invalid.environment.
```suggestion
    /// Environment name was invalid.
```

2023-07-19 17:03 UTC, rjo100 commented on CHANGELOG.md
> +- Limit environment names on check-ins to 64 chars. ([#2309](https://github.com/getsentry/relay/pull/2309))
Yep, got moved during a bad merge

2023-07-19 17:56 UTC, rjo100 commented
I really want to only import the `environment` max chars length to keep everything synced up to one variable as it represents the same object. I can manually copy the `64` limit over but would prefer not to.

2023-07-20 13:55 UTC, jjbayer commented
> I really want to only import the `environment` max chars length to keep everything synced up to one variable as it represents the same object. I can manually copy the `64` limit over but would prefer not to.

How about we define a constant in `relay-common` and import it from both places (`relay-general` and `relay-monitors`)?

2023-07-24 16:49 UTC, rjo100 commented
I think I'm just going to hardcode `64` in `relay-monitors` and update [this comment](https://github.com/getsentry/sentry/blob/7eef24a0858eb2d1868b323f26d0998dcd8cc94a/src/sentry/models/environment.py#L56) in the `sentry` repo mention both instances

2023-07-24 17:31 UTC, rjo100 commented
alright I can't figure out how to make this work. will wait for comments

2023-07-26 08:26 UTC, jjbayer approved these changes
LGTM as-is.

2023-07-26 18:58 UTC, merged