fix(protocol): Fix meta::has_remarks method.
getsentry/relay pull request #2655
Opened 2023-10-25 07:21 UTC by TBS1996

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2023-10-25 07:45 UTC, iker-barriocanal reviewed
Having a test in cases like this could be beneficial I think

2023-10-25 08:08 UTC, TBS1996 commented
> Having a test in cases like this could be beneficial I think

well that would certainly have stopped this bug in the first place. I added a test now!

2023-10-25 08:54 UTC, iker-barriocanal requested changes
Is this the method that's not being used? We should get rid of it in that case.

2023-10-30 09:19 UTC, iker-barriocanal approved these changes

2023-10-30 11:13 UTC, merged