feat(profiling): Add mixed profiles (profile event V2)
getsentry/relay pull request #2685
Opened 2023-11-02 14:44 UTC by krystofwoldrich

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2023-11-02 15:27 UTC, phacops requested changes
I don't think creating a mixed format like this is the right approach. We could add a field to the current Android format to make it backwards compatible (we wouldn't need any change to the pipeline if the field is empty).

You can still reuse some elements of the sample format (like the `Profile` struct) but besides that, let's keep things separate.

2023-11-02 15:27 UTC, phacops commented on relay-profiling/src/profile_version.rs
> +pub enum Version {
Let's keep a specific `Version` enum for each type of profile, inside their respective module.

2023-11-02 17:10 UTC, krystofwoldrich commented
> we wouldn't need any change to the pipeline if the field is empty

I agree adding an extra field on the Android profile is a faster way to go, but it would work only for Android.

The mixed format would allow a general approach for Hybrid SDKs to pack multiple profiles. Compared to that adding a field to the Android profile works only on Android. (Mixed profiles could be used for iOS, Hermes...)

Adding a field on the Android profile moves part of the complexity to SDKs, where the assembled event will change metadata based on the content. (Hermes -> Profiles V1, Hermes + iOS -> Profiles V1, Hermes + Android -> Android Profiles "V0")

The SDK should send one format of metadata no matter the actual profiling data. If needed to reduce the complexity we can change the format in Relay.

2023-11-02 21:06 UTC, phacops commented
Do we actually have to create another format for sample profilers? Why wouldn't we add the samples/stacks/frames the way we have the schema already, mixed in with the rest with adding the proper platform field to frames? I'm not convinced we need a new mixed schema.

Android has always been treated differently because of the binary format it sends us not fitting anything else. For the rest, it seems like the sample format we created fits our needs, even with RN frames and samples mixed in with native frames and samples.

2023-11-03 08:27 UTC, krystofwoldrich commented
The current format works for mixed profiles, but we mixed them on a device at the moment. We also convert RN Hermes profiles on a device. It's still a time-consuming task, but faster than parsing the Android binary trace.

I'm not sure about adding `rnProfile` property to the Android profile is:
- The RN SDK controls the Transactions and Profiles.
- The top-level platform still should be `javascript` not `android`.
- The Android Metadata is different from the V1 profiles. (The RN SDK could create the Android format of metadata, but it seems more like a workaround)

2023-11-09 13:40 UTC, krystofwoldrich commented
Closing this in favor of simpler RN/Android specific format -> https://github.com/getsentry/relay/pull/2706

2023-11-09 13:40 UTC, closed without merging