feat(stats-detectors): Add transaction.op to duration light
getsentry/relay pull request #2881
Opened 2023-12-20 20:16 UTC by Zylphrex

We actually need to extract transaction.op as well since some transactions can have the same name but different ops.

2023-12-20 21:03 UTC, phacops approved these changes

2023-12-21 12:54 UTC, jjbayer requested changes
Couldn't you query this using the metric `d:transactions/duration@millisecond`? Or do you need the `d:transactions/duration_light@millisecond` for performance reasons?

2024-01-04 15:17 UTC, Zylphrex commented
> Couldn't you query this using the metric `d:transactions/duration@millisecond`? Or do you need the `d:transactions/duration_light@millisecond` for performance reasons?

`d:transactions/duration_light@millisecond` was added for performance reasons since we'll never filter any tags. However, one oversight was that we never distinguished between transactions with the same name but different operations.

The main use case for this metric is for statistical detectors where we query for the top transactions + their time series for every project to identify potential regressions.

2024-01-05 08:33 UTC, jjbayer approved these changes
@Zylphrex thanks for the extra context!

2024-01-05 08:33 UTC, merged