feat(spans): Copies exclusive_time from span data into a top level attribute
getsentry/relay pull request #3166
Opened 2024-02-26 22:04 UTC by edwardgou-sentry

Takes `exclusive_time` from span data, and copies it as a top level attribute on the span.

For context, this is required because we enforce the top level `exclusive_time` attribute to be not empty when validating spans. For `otel_span`, we already do this on the `exclusive_time_ns` within the span data, but we do not do this on `span` type items (hence this pr).

2024-02-26 22:27 UTC, edwardgou-sentry commented
The reason why we are sending `exclusive_time` in `data` is because having `exclusive_time` as a toplevel attribute in the payload is less OTel compliant

2024-02-27 08:32 UTC, jjbayer requested changes
> The reason why we are sending exclusive_time in data is because having exclusive_time as a toplevel attribute in the payload is less OTel compliant

@edwardgou-sentry I don't fully get this reasoning. Sentry spans have a different format than OTel spans. They are not OTel compatible, so why could an SDK not send the top-level field?

That said, if this is fix to make span ingestion work for existing SDKs that send `exclusive_time` in the data field, we can merge it.

2024-02-27 14:30 UTC, edwardgou-sentry commented
> > The reason why we are sending exclusive_time in data is because having exclusive_time as a toplevel attribute in the payload is less OTel compliant
> 
> @edwardgou-sentry I don't fully get this reasoning. Sentry spans have a different format than OTel spans. They are not OTel compatible, so why could an SDK not send the top-level field?
> 
> That said, if this is fix to make span ingestion work for existing SDKs that send `exclusive_time` in the data field, we can merge it.

Hey @jjbayer , there's some more context in this pr:
https://github.com/getsentry/sentry-javascript/pull/10704#discussion_r1496693949

We could send `exclusive_time` as a top level field, but we're preferring to send it in `data`. I think part of the reason is because in the sdks we don't separate types between OTel spans and Sentry spans?

cc @AbhiPrasad

2024-02-28 16:24 UTC, edwardgou-sentry commented
Closing this PR since we are agreeing to pass `exclusive_time` as a top level field in envelopes from SDKs, so this normalization is no longer needed

2024-02-28 16:24 UTC, closed without merging