feat: Added span status mapping and integer values from otel
getsentry/relay pull request #348
Opened 2019-12-02 21:18 UTC by mitsuhiko

2019-12-02 21:28 UTC, fpacifici reviewed
Seems good to me, will let @untitaker stamp it since he has a lot more context.

2019-12-02 21:28 UTC, fpacifici commented on py/semaphore/consts.py
> +del _get_span_status_mapping
new line missing

2019-12-03 07:13 UTC, jan-auer reviewed
Just two comments, leaving the final decision to @untitaker.

2019-12-03 07:13 UTC, jan-auer commented on general/src/protocol/contexts.rs
> +                    0 => SpanStatus::Ok,
You could cast this from a u8 with bounds checks, if you’d like to avoid the duplication. Not sure if we do this in `general` already, though.

2019-12-03 07:13 UTC, jan-auer commented on py/semaphore/consts.py
> +        name = normalizer.normalize_event({"contexts": {"trace": {"status": i,},},})[
This is quite extreme :) Just wondering, exporting the enum directly via the CABI, or exposing a function that returns a static name was not an option?

2019-12-03 11:28 UTC, untitaker requested changes
Let's create a macro that takes the mapping as argument, and generates three pieces of code: the two rust mappings and some C constants.

I believe we can completely omit `repr(u8)` from the enum if we're not going to make use of it via transmute

2019-12-04 14:12 UTC, mitsuhiko commented
I'm hardcoding the table a second time for now until I get time to refactor this with a macro. We already have a few other mappings that would benefit from a derive.

2019-12-04 15:06 UTC, untitaker approved these changes
I am not happy

2019-12-04 23:10 UTC, merged

2019-12-04 23:10 UTC, mitsuhiko commented
Equally unhappy