feat(replays): Add video entry to DataCategory enum
getsentry/relay pull request #3847
Opened 2024-07-22 17:06 UTC by cmanallen

During the beta period we're not emitting accepted replay outcomes for mobile replays (to prevent customer's from being billed).  Tracking usage through Looker is difficult without this data.  We want to emit a non-billed outcome in our consumer for tracking purposes.  This category is assumed to be temporary.

Related: https://github.com/getsentry/team-replay/issues/452

2024-07-22 18:32 UTC, Dav1dde requested changes
Please follow the docs right below your change:

https://github.com/getsentry/relay/blob/93144ee6d5b9fce17cf8a964c1a417e6d1111152/relay-base-schema/src/data_category.rs#L91-L96

2024-07-22 19:04 UTC, Dav1dde commented
Ah, I forgot before. Please also add a changelog entry to `py/CHANGELOG.md` since this will be a change in the Python lib and Sentry (or consumers) will depend on that change.

2024-07-22 19:06 UTC, cmanallen commented
@Dav1dde Any ideas?

```
(.venv) ➜  relay-cabi git:(cmanallen/replays-add-video-data-category) ✗ make header
cbindgen -c cbindgen.toml . -o include/relay.h
make: cbindgen: No such file or directory
make: *** [include/relay.h] Error 1
(.venv) ➜  relay-cabi git:(cmanallen/replays-add-video-data-category) ✗ ls
Cargo.toml    Makefile      cbindgen.toml include       src
(.venv) ➜  relay-cabi git:(cmanallen/replays-add-video-data-category) ✗ ls include
relay.h
```

2024-07-22 19:07 UTC, cmanallen commented
@Dav1dde Oh, I don't think I have cbindgen installed.  Let's see if that fixes it.

2024-07-23 12:11 UTC, Dav1dde approved these changes

2024-07-23 12:11 UTC, Dav1dde commented on relay-quotas/src/quota.rs
> +            DataCategory::Unknown | DataCategory::ReplayVideo => None,
This could go with the `Self::Count` block I think.

2024-07-23 16:40 UTC, merged