feat(native): Set sdk.name for events created from minidumps
getsentry/relay pull request #4313
Opened 2024-11-29 10:44 UTC by tobias-wilfert

Sets the sdk.name for events created out of minidumps to `minidump`, mimicking the logic that we currently have for unreal.

Not sure we can add more detail than just `minidump`? Presumably something like this could work but I am not sure if we want to do that:
```rs
  let more_detailed_sdk_name = if minidump.get_stream::<MinidumpCrashpadInfo>().is_ok() {
      "minidump.crashpad"
  } else if minidump.get_stream::<minidump::MinidumpBreakpadInfo>().is_ok() {
      "minidump.breakpad"
  } else {
      "minidump.unknown"
  };
```

Fix: https://github.com/getsentry/relay/issues/4236

2024-11-29 10:48 UTC, loewenheim requested changes

2024-11-29 10:48 UTC, loewenheim commented on relay-server/src/utils/native.rs
> +const CLIENT_SDK_NAME: &str = "minidump";
I would give this a name to indicate that it applies specifically to minidumps.

2024-11-29 10:50 UTC, loewenheim commented
Adding the more specific names sounds like a good idea to me.

2024-11-29 10:51 UTC, Dav1dde reviewed
We can start with a simple sdk name for everything then see if it still makes sense to invest more time into tagging the sdk name with more information.

Would be good if you modify existing tests to also assert the client sdk name, we should have at least some tests that can be easily extended to assert the SDK name.

2024-11-29 12:54 UTC, loewenheim approved these changes

2024-11-29 13:58 UTC, merged

2024-12-06 04:38 UTC, bruno-garcia commented on relay-server/src/utils/native.rs
> +    event.client_sdk.get_or_insert_with(|| ClientSdkInfo {
will this override the SDK set in the client? Or this only affects minidumps from the minidump endpoint?

Meaning if it's `sentry-native` attaching a minidump from crashpad, will it no longer send `sentry-native`?