fix(schema): Mechanism type is not really required
getsentry/relay pull request #711
Opened 2020-08-12 11:00 UTC by untitaker

Would like to make this nullable as the Python SDK wants to send exceptions where the errno is known but the mechanism not.

2020-08-17 11:50 UTC, jan-auer requested changes
The type is not effectively required because of the (undocumented) legacy schema. The new schema does require it and it should remain required.

2020-08-17 11:56 UTC, untitaker commented
Can we move `errno` outside of mechanism then?

2020-08-17 12:00 UTC, jan-auer commented
> Can we move `errno` outside of mechanism then?

Why would we do that? I don't see how this has to do with the mechanism type being required. Just send the `generic` default value for `mechanism.type`.

2020-08-17 12:04 UTC, untitaker commented
The default type for `mechanism` is null though. We can make those two synonymous but right now they behave differently in UI and Snuba, and what's the point of sending `generic` explicitly if it's supposed to be the default?

2020-08-17 12:57 UTC, jan-auer commented
Ah, I see. So you're not catching a signal but rather you just want to log the errno. Let's bring this up in TSC and create a DACI for this. It is indeed something that mechanism was not designed for.

2020-08-27 18:14 UTC, untitaker commented
The outcome of the TSC was that I should use `generic` as mechanism type :(

2020-08-27 18:14 UTC, closed without merging