feat: Override for project configs
getsentry/relay pull request #78
Opened 2018-09-04 14:56 UTC by untitaker

2018-09-04 15:00 UTC, untitaker commented
The apparent motivation for the "passive config mode" feature is to avoid writing a project config UI for sentry, the PR offers an alternative. However, relays still unconditionally authenticate.

2018-09-05 06:20 UTC, mitsuhiko requested changes

2018-09-05 06:20 UTC, mitsuhiko commented on common/src/config.rs
> +    pub slug: String,
We should make this optional

2018-09-05 07:48 UTC, untitaker commented
One ugly thing I found is that `ProjectConfig` and `StaticProjectState` have camelCase keys, while the other keys don't. It seems easiest to change everything to camelcase...

2018-09-07 09:35 UTC, untitaker commented
- [ ] make one file per project config

2018-09-10 17:04 UTC, closed without merging