feat: Ability to override project configs locally
getsentry/relay pull request #84
Opened 2018-09-11 08:59 UTC by untitaker

This is a rewrite of #78. Introduces own worker pool for blocking IO.

2018-09-11 09:11 UTC, untitaker commented
@jan-auer mentioned that event processing uses SyncArbiter... we should use either CpuPool or SyncArbiter.

2018-09-11 09:33 UTC, mitsuhiko requested changes
Just a tiny change request. I think cpu pool is good but i wonder when to pick this vs sync arbiter.

2018-09-11 09:33 UTC, mitsuhiko commented on common/src/config.rs
> +        self.path.join(format!("projects/{}.json", id))
just for consistency this should be .join() + .join()

2018-09-11 12:38 UTC, untitaker commented
Apparently SyncArbiter would require the entire actor to be sync... I am not sure if that's a great idea? I would like to have a shared pool for all custom IO activity as opposed to making this actor mulltithreaded (or having a dedicated actor for static project configs)

2018-09-13 07:13 UTC, jan-auer approved these changes
LGTM, and generally very nice. A couple of style nit picks attached. 

However, I agree with @mitsuhiko that we should aim to use `SyncArbiter` here, which would reduce some of the verbosity / messy-ness of the cpu_pool code.

2018-09-13 07:13 UTC, jan-auer commented on common/src/config.rs
> +    pub worker_threads: Option<usize>,
_nit_: At this position, this setting will be put into the default config. Depending on what we plan to do with the processing worker pool, we could try to omit this from the default generated content.

See: https://github.com/getsentry/semaphore/blob/b2ab6d2b25dff36cedabe73db0a84d8780cb49d9/server/src/actors/events.rs#L183-L187

2018-09-13 07:13 UTC, jan-auer commented on common/src/config.rs
> +        self.values.relay.worker_threads.unwrap_or(20)
_nit:_ This would ideally use something like `num_cpus` to be in some relation to the host. Otherwise, if we really have a static configuration, we should make the setting non-option and just put `20` in the `Default` implementation (mostly for consistency reasons).

2018-09-13 07:13 UTC, jan-auer commented on server/src/actors/project.rs
> +    FromDisk,
_nit_: Ideally, these would just be `Upstream` and `Disk`, see [clippy::enum_variant_names](https://rust-lang-nursery.github.io/rust-clippy/current/index.html#enum_variant_names) (currently disabled for us, though).

2018-09-13 15:25 UTC, untitaker commented
@jan-auer and I decided on something entirely else, closing

2018-09-13 15:25 UTC, closed without merging