fix: Send key_id in partial project config
getsentry/relay pull request #854
Opened 2020-11-25 14:47 UTC by tonyo

With this change external relays will receive DSN ids as part of (partial) project config. This will allow trusted external relays to emit proper outcomes.

2020-11-25 15:01 UTC, jan-auer requested changes
Thanks! You can simplify this further as indicated in the comment below.

Note that this also has to be fixed in Sentry [here](https://github.com/getsentry/sentry/blob/917a3eaed2e6cad0ec95392f1b41b0cfc9c7bfe2/src%2Fsentry%2Frelay%2Fconfig.py#L46).

2020-11-25 15:01 UTC, jan-auer commented on relay-server/src/actors/project.rs
> +        pub numeric_id: Option<u64>,
This is now equivalent to `PublicKeyConfig`, so you can remove the entire module.

2020-11-26 13:53 UTC, tonyo commented
When adding the test I realized, that we have buggy behavior that might result in duplicated outcomes when e.g. rate-limiting. Marked the test as xfail, will fix it after the outcome behavior is updated.

2020-11-26 15:27 UTC, jan-auer approved these changes
Thank you. Please remember to also update this in Sentry.

2020-11-26 16:49 UTC, merged