fix(doc): Fix doc string on redis script
getsentry/relay pull request #873
Opened 2020-12-04 17:15 UTC by RaduW

minor, fix doc string on redis script
#skip-changelog

2020-12-04 17:17 UTC, untitaker approved these changes

2020-12-04 18:42 UTC, jan-auer requested changes
LGTM, but please revert changes to `Cargo.lock`.

2020-12-04 21:05 UTC, untitaker commented
wow I missed those as github helpfully hid the large diff 👍 💯

2020-12-07 07:58 UTC, RaduW commented
Hmm, good catch, absolutely no idea how I got to modify the cargo.lock file.

2020-12-07 10:49 UTC, merged